CREATE TABLE Superhero (
	SuperheroID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name VARCHAR(150),
	Alias VARCHAR(50),
	Origin VARCHAR(255),
);

CREATE TABLE Assistant (
	AssistantID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name VARCHAR(150),
);

CREATE TABLE Power (
	PowerID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name VARCHAR(50),
	Description VARCHAR(255),
);
	